fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    serializer:
        serialize_null: true
    param_fetcher_listener: force
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json', prefer_extension: true }


    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes: { Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404, FOS\RestBundle\Exception\InvalidParameterException: 400, \Exception: 500 }
        messages: { Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true, FOS\RestBundle\Exception\InvalidParameterException: true, \Exception: true }
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
